apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cht.service: haproxy
  name: cht-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      cht.service: haproxy
  strategy: {}
  template:
    metadata:
      labels:
        cht.service: haproxy
    spec:
      containers:
        - env:
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_PASSWORD
            - name: COUCHDB_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: couchdb-servers-configmap
                  key: COUCHDB_SERVERS
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_USER
            - name: HAPROXY_IP
              value: 0.0.0.0
            - name: HAPROXY_PORT
              value: "5984"
            - name: HEALTHCHECK_ADDR
              value: healthcheck.cht-dev-namespace.svc.cluster.local
          image: public.ecr.aws/s5s3h4s7/cht-haproxy:4.1.1-4.1.1
          name: haproxy
          ports:
            - containerPort: 5984
          resources: {}
      hostname: haproxy
      restartPolicy: Always
status: {}
