apiVersion: v1
kind: Service
metadata:
  labels:
    cht.service: couchdb-3
  name: couchdb-3
spec:
  ports:
    - name: couchdb3-service
      port: 5984
      protocol: TCP
      targetPort: 5984
    - name: epmd
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: erlang
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    cht.service: couchdb-3
status:
  loadBalancer: {}
