apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-v3-haproxy
  annotations:
    haproxy.version: medicmobile/haproxy:rc-1.18
  labels:
    cht.service: dev-v3-haproxy
    app: dev-v3
spec:
  selector:
    matchLabels:
      cht.service: dev-v3-haproxy
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        haproxy.version: medicmobile/haproxy:rc-1.18
      labels:
        cht.service: dev-v3-haproxy
        app: dev-v3
    spec:
      containers:
      - image: medicmobile/haproxy:rc-1.18
        name: haproxy
        envFrom:
        - secretRef:
            name: "secret-dev-v3-env"
        resources: {}
      restartPolicy: Always
status: {}
