apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-v3-medic-sentinel
  annotations:
    medic-sentinel.version: medicmobile/medic-sentinel:3.10.0-010520-test1
  labels:
    cht.service: dev-medic-sentinel
    app: dev-v3  
spec:
  selector:
    matchLabels:
      cht.service: dev-v3-medic-sentinel
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        medic-sentinel.version: medicmobile/medic-sentinel:3.10.0-010520-test1
      labels:
        cht.service: dev-v3-medic-sentinel
        app: dev-v3 
    spec:
      containers:
      - name: medic-sentinel
        image: medicmobile/medic-sentinel:3.10.0-010520-test1
        envFrom:
        - secretRef:
            name: "secret-dev-v3-env"
        resources: {}
      restartPolicy: Always
status: {}
