apiVersion: v1
kind: Secret
metadata:
  name: cht-couchdb-credentials
type: Opaque
stringData:
  COUCHDB_PASSWORD: {{ .Values.couchdb.password }}
  COUCHDB_SECRET: {{ .Values.couchdb.secret }}
  COUCHDB_USER: {{ .Values.couchdb.user }}
  COUCHDB_UUID: {{ .Values.couchdb.uuid }}
  COUCH_URL: http://{{ .Values.couchdb.user }}:{{ .Values.couchdb.password }}@haproxy.{{ .Values.namespace }}.svc.cluster.local:5984/medic
