blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://docs.communityhealthtoolkit.org/
    about: Read the CHT documentation.
  - name: ðŸ’¬ Ask on the forum
    url: https://forum.communityhealthtoolkit.org/
    about: The best place for asking for support or general purpose questions.
  - name: ðŸ‘¥ Get involved
    url: https://docs.communityhealthtoolkit.org/community/
    about: Learn how to contribute.
