apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cht.service: api
  name: cht-api
spec:
  replicas: 1
  selector:
    matchLabels:
      cht.service: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        cht.service: api
    spec:
      containers:
        - env:
            - name: BUILDS_URL
              value: https://staging.dev.medicmobile.org/_couch/builds_4
            - name: COUCH_URL
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCH_URL
            - name: UPGRADE_SERVICE_URL
              value: http://upgrade-service.{{ .Values.namespace }}.svc.cluster.local:5008
          image: public.ecr.aws/medic/cht-api:{{ .Values.cht_image_tag }}
          name: cht-api
          ports:
            - containerPort: 5988
          resources: {}
      restartPolicy: Always
status: {}
