{{- if and (eq .Values.environment "remote") (eq .Values.remote.existingEBS "true") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-pv-{{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.remote.existingEBSVolumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: {{ .Values.remote.existingEBSVolumeID }}
    fsType: ext4
    volumeAttributes:
      partition: "0"
{{- end }}
