{{- if not .Values.couchdb.clusteredCouch_enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cht.service: couchdb-claim0
  name: couchdb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.couchdb.single_node_storageSize }}
  storageClassName: ebs-gp2
status: {}
{{- end }}
