apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cht.service: couchdb-3-claim0
  name: couchdb-3-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.couchdb.node3_storageSize }}
  persistentVolumeReclaimPolicy: Retain
status: {}
