apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-servers-configmap
data:
  {{- if .Values.clusteredCouch_enabled }}
  COUCHDB_SERVERS: couchdb-1.{{ .Values.namespace }}.svc.cluster.local,couchdb-2.{{ .Values.namespace }}.svc.cluster.local,couchdb-3.{{ .Values.namespace }}.svc.cluster.local
  COUCHDB_SYNC_ADMINS_NODE: couchdb-1.{{ .Values.namespace }}.svc.cluster.local
  {{- else }}
  COUCHDB_SERVERS: couchdb.{{ .Values.namespace }}.svc.cluster.local
  {{- end }}
