{{- if and (not .Values.couchdb.clusteredCouch_enabled) (eq .Values.environment "remote") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cht.service: couchdb-claim0
  name: couchdb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.couchdb.couchdb_node_storage_size }}
  {{- if eq .Values.remote.existingEBS "true" }}
  volumeName: couchdb-pv
  storageClassName: ""
  {{- else }}
  storageClassName: ebs-gp2
  {{- end }}
status: {}
{{- end }}
