apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cht.service: couchdb-2-claim0
  name: couchdb-2-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.couchdb.node2_storageSize }}
  persistentVolumeReclaimPolicy: Retain
status: {}
