apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cht.service: healthcheck
  name: cht-haproxy-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      cht.service: healthcheck
  strategy: {}
  template:
    metadata:
      labels:
        cht.service: healthcheck
    spec:
      containers:
        - env:
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_PASSWORD
            - name: COUCHDB_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: couchdb-servers-configmap
                  key: COUCHDB_SERVERS
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: cht-couchdb-credentials
                  key: COUCHDB_USER
          image: {{ .Values.upstream_servers.docker_registry }}/cht-haproxy-healthcheck:{{ .Values.cht_image_tag }}
          name: cht-haproxy-healthcheck
          resources: {}
          ports:
            - containerPort: 5555
      restartPolicy: Always
