name: Delete old published artefacts

on:
  schedule:
    - cron:  '0 3 * * *' # Run every day at 3am

env:
  MARKET_URL: ${{ secrets.AUTH_MARKET_URL }}

jobs:
  cleanup:
    name: Deleting old published artefacts
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Cleanup
      run: |
        cd scripts/ci
        npm ci
        node ./cleanup.js
