name: Build and test performance

on: 
  push:
    branches: 
      - performancetotal

jobs: 

  #job0: 

  build:
    uses: ./.github/workflows/build.yml
    with:
      config-path: .github/labeler.yml
    #secrets: inherit
    #env: inherit

  
  # tests:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     config-path: .github/labeler.yml
  #   grunt-cmd: ['ci-webdriver-default']
  #   needs: build
  #   name: test reusable
    # env: inherit

    

  