name: Build and test performance

on: 
  push:
    branches: 
      - performancetotal

jobs: 

  #job0: 

  build:
    uses: ./.github/workflows/build.yml@main

  job2:
    runs-on: ubuntu-latest
    #needs: build
    name: testing reusable
    steps:
      - run: echo "${{ needs.build.outputs }}"
  # tests:
  #   uses: ./.github/workflows/reusable-workflow-example-called.yml
  #   with:
  #     grunt-cmd: ['ci-webdriver-default']
  #   needs: build
  #   name: test reusable
  #   env: inherit

    

  