name: Release notes generator

on:
  workflow_dispatch:
  push:
    tags:
      - "*-beta.*"

jobs:
  release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Use Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Deps & Create Markdown (or error)
        run: |
          cd scripts
          npm ci
          cd release-notes
          GITHUB_TOKEN=${{ secrets.DEPLOY_TO_GITHUB_PAGES }} node index.js > ~/release-notes.md
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: release-notes
          path: ~/release-notes.md
          retention-days: 10
      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'